.TH PC3G11 1  "February 24, 2012" "version 1.0" "USER MANNUAL"
.SH NAME
info6005_pc3g11 \- the Simple PHP RSS Reader for INFO6005
.SH COMMANDS
get_news (for feeds)
php index.php (for feeds)
php index.php \-\-help (for help)
.SH INTERFACE USE
pplications \-\-> Internet \-\-> info6005-pc3g11.desktop
.SH DESCRIPTION
This is part of a coursework for Students on the INFO6005 course at the University of Southampton.
In this course students are expected to package some code for distribution on the debian/ubuntu platform
.SH MANNUAL COMMANDS
.PP
man info6005-pc3g11
.PP
man get_news
.SH AUTHORS
Panayiotis Christofi - pc3g11@soton.ac.uk
.PP
University of Southamoton, Electronics and Computer Science
.SH EXIT MANNUAL
Press: wq
